spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: true  # 에러 발생해도 계속 진행

  mail:
    host: smtp.gmail.com
    port: 587
    username: labify01@gmail.com
    password: wywgbtgojtrcijll
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분 (이메일 인증 코드 만료 시간)

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000          # 15분
  refresh-expiration: 604800000      # 7일
  issuer: labify-backend             # 토큰 발급 주체

ai-server:
  url: ${AI_SERVER_URL} # FastAPI 서버 주소